# Generated by Django 3.1.5 on 2021-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on witch the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on witch the object was last modified', verbose_name='modified_at')),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'newsletter_contacts',
            },
        ),
    ]
