# Generated by Django 3.1.5 on 2021-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercontact',
            name='ip_address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettercontact',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='newslettercontact',
            name='user_agent',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
