# Generated by Django 3.1.5 on 2021-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210113_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercontact',
            name='user_agent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
