# Generated by Django 3.1.5 on 2021-01-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210113_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercontact',
            name='user_agent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
