# Generated by Django 3.1.5 on 2021-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210114_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercontact',
            name='user_agent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
